[package]
name = "mediacenter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-web-lab = "0"
actix-files = "0"
tera = "1.8"
log = "0"
env_logger = "0"
